server:
  port: 8081
  servlet:
    context-path: /lms

spring:
  liquibase:
    change-log: classpath:db/library-management-system-schema.xml
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:lms
    username: dbadmin
    password: dbadmin
  h2:
    console:
      path: /h2
      enabled: true
